### ISSUE TITLE
Installasjon på Linux

### ISSUE THREAD

**Issue by gahjelle** [atlefren/gd18_python_demo#1]
Hei Atle,

jeg prøvde å installere på Linux og fikk følgende feilmelding:

```
~/gd18_python_demo > conda env create -f environment.yml 
Solving environment: failed

ResolvePackageNotFound: 
  - vs2010_runtime==10.00.40219.1=2
  - vc==10=0
  - setuptools==27.2.0=py34_1
```
`vs2010_runtime` høres veldig Windows ut?

Jeg laget meg i stedet et environment vha
```
~/gd18_python_demo > conda create -n geomatikkdagene18 python geopandas geojson mplleaflet ipython jupyter -c conda-forge
```
Og det fungerer flott på eksempel-notebook'ene (disse ser ut til å bare bruke geopandas så har ikke testet geojson og mplleaflet).

**Comment by LtGlahn** [comment]
Takk for tips. Møtte samme problem på min linux-boks, fiksa i siste versjon.
